React Todo List
batoorsohail/react-todo-app pull request #1
Opened 2023-03-06 09:11 UTC by batoorsohail

### In this project, we added the followings:

- [ ] Adding tasks
- [ ] Deleting tasks
- [ ] Checking complete task
- [ ] Basic Styles

2023-03-08 19:52 UTC, Odongo006 requested changes
Hello @batoorsohail , Great job 👏  on this pull request! I can see that you've put a lot of effort into ensuring that there are no linter errors and that you've followed the correct gitflow process. Your descriptive pull request made it easy to understand the changes you've made and their purpose 💯 👍.

It's always refreshing to see a developer who pays attention to detail and takes the time to ensure that their code is not only functional but also maintainable. Your commitment to producing high-quality code is evident in this pull request.

Thank you for your hard work and dedication. Your efforts are greatly appreciated. There are some issues that you still need to work on to go to the next project but you are almost there!

Highlights
 Good job overall following the template design ✅
 Good commit history ✅
 Good PR title/description ✅
 All Linters passed ✅
Required Changes ♻️
Check the comments under the review.

2023-03-08 19:52 UTC, Odongo006 commented on README.md
> +# 📖 Awesome Books <a name="about-project"></a>
Provide a brief descriptive introduction about the project. This will help users understand the purpose of the project quickly.

2023-03-08 19:52 UTC, Odongo006 commented on README.md
> +You can deploy this project using:
I noticed that the deployment link is not included in your pull request; In order to properly review and test your changes, it would be helpful if you could provide a working deployment link.

2023-03-08 19:52 UTC, Odongo006 commented on README.md
> +To run the project, execute the following command:
Thank you for submitting your pull request. I noticed that there is no link to your project included in the pull request description. It would be really helpful for the reviewers and potential users of your project if you could include a link to your project in the description.

2023-03-09 04:42 UTC, batoorsohail commented
Thanks, @Odongo006 🙌 for reviewing my project,
I will make changes to the Readme file and push them. 😄

2023-03-09 04:49 UTC, batoorsohail commented on README.md
> +# 📖 Awesome Books <a name="about-project"></a>
Thanks, @Odongo006 for reminding that. I added the project descriptions below line 28. 😃

2023-03-18 17:57 UTC, merged